### ISSUE TITLE
Add support for hypergraphs

### ISSUE THREAD

**Issue by MaxXor** [Washi1337/Rivers#1]
Check [this](https://en.wikipedia.org/wiki/Hypergraph) out :D

**Comment by Washi1337** [comment]
I have little knowledge about hypergraphs, but after reading up a bit about them, it seems they can be emulated using clusters or subgraphs in a normal graph, which is supported:

```csharp
var graph = new Graph();
var n1 = graph.Nodes.Add("1");
var n2 = graph.Nodes.Add("2");
graph.SubGraphs.Add(new SubGraph(n1, n2));
```

The `SubGraph` class has a `Nodes` collection containing each node in the cluster, and each `Node` instance has a `SubGraphs` collection, containing all subgraphs the node is part of.

Is there any feature that you are particularly interested in that is exclusive to hypergraphs?

**Comment by MaxXor** [comment]
Hm, does this workaround allow to create edges with more than two vertices?

**Comment by Washi1337** [comment]
A hyperedge is really just a set of nodes within a graph. Since a subgraph would fit that same description, it could be used to model the hyperedges. Even the ones with more than two vertices in them. Or am I missing something and are there more properties involved?

**Comment by MaxXor** [comment]
Yes, that should work thanks.
