### ISSUE TITLE
Publish NuGet package

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [Washi1337/Rivers#5]
I'd like to use Rivers in my project, and using a submodule has various downsides for me:
- Latest commit targets net471, which I can't compile on Linux (I need to check out an older commit)
- No (semantic) versioning
- Requires including Rivers as a project in my solution.

I'd like to propose publishing a NuGet package to make consuming this library easier. It should also help with discoverability for other people.

**Comment by Washi1337** [comment]
Thanks for taking interest in the project. I will prepare a nuget package either today or tomorrow. 

In the meantime, you can still build the library using the netstandard platform only using:
```
dotnet build --framework=netstandard2.0
```

**Comment by Washi1337** [comment]
I just configured AppVeyor to automatically push updates on master to NuGet. The package should be validated and indexed by NuGet within an hour.

**Comment by HoLLy-HaCKeR** [comment]
Seems to be up now, thanks!

**Comment by HoLLy-HaCKeR** [comment]
It seems like you have an API key in your .appveyor file, if that's not intended you probably want to revoke the key, edit the appveyor file and move it to your server-side configuration.

**Comment by Washi1337** [comment]
The key you found in appveyor.yml is the encrypted version of the actual API key that can only be decrypted by an AppVeyor account that holds the decryption key. Since my account only holds this key, there should be no concern of third parties pushing illegitimate/malicious updates unless my nuget account gets hacked.
