### ISSUE TITLE
Single word attributes that start with digits are not quoted

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [Washi1337/Rivers#7]
If I add UserData starting with `0x` to a node or edge, Rivers will not quote it. Certain viewers (such as [xdot](https://github.com/jrfonseca/xdot.py)) will try to read these attributes as integers and crash.

Example:
```dot
strict digraph {
"_0001" [label=Add];    // works
"_0002" [label=0x70];   // does not work
"_0003" [label="0x70"]; // works
}
```

As a temporary workaround, I can pad the values with spaces.

**Comment by Washi1337** [comment]
Seems I disregarded one important detail in the specification of the dot language.

The [specification](https://www.graphviz.org/doc/info/lang.html) states:
> An ID is one of the following:
> - Any string of alphabetic ([a-zA-Z\200-\377]) characters, underscores ('_') or digits ([0-9]), **not beginning with a digit**

As a consequence:
```dot
strict digraph {
    0x0 -> 0x1
}
```
Should be parsed as 3 nodes (0, x0, x1) and one edge between x0 and 0.
